language: cpp

cache:
    directories:
        - "dl"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y make aria2 xz-utils

before_script:
    - make download

script:
    - export ARCH=arm
    - export CROSS_COMPILE=arm-linux-gnueabihf-
    - make -j`getconf _NPROCESSORS_ONLN`
